# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

variables:
- name: ContainerRegistry
  ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}: # only works if you have a main branch
    value: cc34f6f4-3d14-4162-bbbc-9aa3b8680625
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}: # only works if you have a dev branch
    value: 7e66b725-08c3-4a7b-99e6-23ea681b90c6
- name: BuildCommand
  ${{ if eq(variables['Build.SourceBranchName'], 'prod') }}: # only works if you have a main branch
    value: '**/Dockerfile'
  ${{ if eq(variables['Build.SourceBranchName'], 'dev') }}: # only works if you have a dev branch
    value: '**/Dockerfile-dev'

trigger:
- dev
- prod

pool:
  vmImage: ubuntu-latest

steps:
- task: Docker@2
  displayName: "Build and Push Docker Image"
  inputs:
    containerRegistry: $(ContainerRegistry)
    repository: '$(Build.Repository.Name)'
    command: 'buildAndPush'
    Dockerfile: $(BuildCommand)
    tags: '$(Build.SourceBranchName)'
    arguments: '--build-arg BUILD_CMD=$(BuildCommand)'